import type { MessageCandidate, Task, CalendarItem } from '../types.ts';
import { esc, parseJson, smartTaskTitle, fmtEvent, srcBadge } from '../utils/helpers.ts';
const when=(d:string|null)=>d?new Date(d.replace(' ','T')).toLocaleDateString('en',{month:'short',day:'numeric'})+' · '+new Date(d.replace(' ','T')).toLocaleTimeString('en',{hour:'numeric',minute:'2-digit'}):'';;
const meta=(x:{source_details:string|null})=>parseJson(x.source_details);
const ruleBadges=(m:MessageCandidate)=>{const d=meta(m),conf=Number(d.calendar_confidence||m.score||0),pct=conf?`<span class="rule-badge rule-badge-dim">${Math.round(conf*100)}% conf</span>`:'';if(d.category==='calendar-review')return `<span class="rule-badge rule-badge-cal">📅 date+time detected</span>${pct}`;if(d.capture_mode==='self_text'||d.source==='self')return `<span class="rule-badge rule-badge-self">✍️ self-text command</span>${pct}`;if(d.reason==='reply')return `<span class="rule-badge rule-badge-reply">↩️ reply-needed</span>${pct}`;if(d.reason==='medical'||d.category==='medical-admin')return `<span class="rule-badge rule-badge-med">🏥 medical/admin</span>${pct}`;if(d.reason==='appointment')return `<span class="rule-badge rule-badge-cal">📅 appointment pattern</span>${pct}`;return `<span class="rule-badge rule-badge-dim">📋 task candidate</span>${pct}`;};
const guess=(m:MessageCandidate)=>{const d=meta(m),raw=(d.event_title||d.title||m.message_text||'').replace(/^(calendar event|event):\s*/i,'').trim(),provider=(d.provider||'').trim();return (provider&&!raw.toLowerCase().includes(provider.toLowerCase())?`${provider}: ${raw}`:raw).slice(0,120)||'Review item';};
const candidate=(m:MessageCandidate)=>{const d=meta(m),isCal=d.category==='calendar-review',date=d.due_date?` · ${d.due_date}${d.starts_at?` ${d.starts_at}`:''}`:'' ,eventOk=!!d.due_date;return `<div class="task-card"><div class="task-content"><div class="task-title">${esc(guess(m))}</div><div class="task-description">${esc(m.message_text.slice(0,180))}</div><div class="task-meta" style="flex-wrap:wrap;gap:4px;margin-top:6px">${isCal?'<span class="task-badge badge-email">📅 Calendar review</span>':'<span class="task-badge badge-default">📝 Task review</span>'}<span class="task-date">${esc(when(m.message_date)+date)}</span>${ruleBadges(m)}</div></div><div class="task-actions" style="opacity:1;flex-wrap:wrap;justify-content:flex-end"><button class="btn-secondary" onclick="editCandidate(${m.id})">Edit</button><button class="btn-secondary" onclick="approveCandidateTask(${m.id})">✓ Task</button><button class="btn-secondary" ${eventOk?'':'disabled title="Needs a date"'} onclick="approveCandidateEvent(${m.id})">📅 Event</button><button class="btn-secondary" onclick="dismissReview(${m.id})">✕</button></div></div>`;};
const bulkDismiss=(items:MessageCandidate[])=>{const texts=items.map(m=>m.message_text.toLowerCase()),hasF=texts.some(t=>/payment|balance|transaction|statement|invoice/.test(t)),hasD=texts.some(t=>/delivery|shipping|package|tracking|shipment/.test(t)),hasN=texts.some(t=>/your appointment reminder|you have a new message|verification code|sign.?in alert/.test(t));if(!hasF&&!hasD&&!hasN)return'';const btns:string[]=[];if(hasF)btns.push(`<button class="btn-secondary" onclick="bulkDismissClass('finance')">Dismiss finance alerts</button>`);if(hasD)btns.push(`<button class="btn-secondary" onclick="bulkDismissClass('delivery')">Dismiss delivery notices</button>`);if(hasN)btns.push(`<button class="btn-secondary" onclick="bulkDismissClass('notification')">Dismiss notifications</button>`);return `<div class="bulk-dismiss-row">${btns.join('')}</div>`;};
const recentTask=(t:Task)=>`<div class="task-card"><div class="task-content" onclick="viewTask(${t.id})"><div class="task-title">${esc(smartTaskTitle(t))}</div><div class="task-meta">${srcBadge(t.source)}<span class="task-date">Created ${esc(when(t.created_at))}</span></div></div><div class="task-actions" style="opacity:1"><button class="btn-secondary" onclick="viewTask(${t.id})">Open</button></div></div>`;
const recentEvent=(i:CalendarItem)=>`<div class="task-card"><div class="task-content" onclick="viewCalendarItem(${i.id})"><div class="task-title">${esc(i.title)}</div><div class="task-meta"><span class="task-badge badge-email">📅 Calendar</span><span class="task-date">${esc(fmtEvent(i))}</span></div></div><div class="task-actions" style="opacity:1"><button class="btn-secondary" onclick="viewCalendarItem(${i.id})">Open</button></div></div>`;
const section=(title:string,rows:string[],empty:string,count:number,bulk='')=>`<div class="section"><div class="section-header"><div class="section-title">${title}<span class="section-count">${count}</span></div></div>${bulk}${rows.length?`<div class="task-list">${rows.join('')}</div>`:`<div class="empty-state" style="padding:20px 16px"><div class="empty-title" style="font-size:15px">${empty}</div></div>`}</div>`;
export function renderMessages(items:MessageCandidate[],recentTasks:Task[]=[],recentEvents:CalendarItem[]=[]):string{
  const cal=items.filter(x=>meta(x).category==='calendar-review'), task=items.filter(x=>meta(x).category!=='calendar-review');
  const recent=[...recentTasks.map(recentTask),...recentEvents.map(recentEvent)].slice(0,10);
  return `<div class="section"><div class="section-header"><div class="section-title">🧾 Review inbox</div></div><div class="instruction-card"><div class="instr-title">Approve, convert, or dismiss</div><div class="instr-desc">Low-confidence candidates wait here before becoming work. Click <strong>Edit</strong> to tweak title/date/type before approving. Rule badges explain why each item was held.</div></div></div>${section('📅 Needs calendar review',cal.map(candidate),'No calendar candidates waiting.',cal.length,bulkDismiss(cal))}${section('📝 Needs task review',task.map(candidate),'No task candidates waiting.',task.length,bulkDismiss(task))}${section('✨ Recently auto-created',recent,'Nothing recent to inspect.',recent.length)}`;
}

