import type { Task, CalendarItem } from '../types.ts';
export const APP_ID='757e7738-6b5a-4f00-a306-b1dd4f382fea';
export const esc=(s='')=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
export const parseJson=(s:string|null)=>{try{return s?JSON.parse(s):{};}catch{return {};}};
export const parsePlan=(s:string|null)=>{try{return JSON.parse(s||'[]') as string[];}catch{return [];}};
export const hasTag=(t:{tags?:string|null},tag:string)=>(t.tags||'').split(',').map(x=>x.trim()).includes(tag);
export const isSomeday=(t:{tags?:string|null})=>hasTag(t,'someday');
export function formatDue(d:string|null){ if(!d) return {text:'',cls:''}; const t=new Date(); t.setHours(0,0,0,0); const x=new Date(d+'T00:00:00'); const diff=Math.round((x.getTime()-t.getTime())/86400000); if(diff<0) return {text:`${Math.abs(diff)}d overdue`,cls:'overdue'}; if(!diff) return {text:'Due today',cls:'due-today'}; if(diff===1) return {text:'Due tomorrow',cls:''}; if(diff<=7) return {text:`Due ${x.toLocaleDateString('en',{weekday:'short'})}`,cls:''}; return {text:`Due ${x.toLocaleDateString('en',{month:'short',day:'numeric'})}`,cls:''}; }
export const pLabel=(p:number)=>['','Urgent','High','Medium','Low'][p]||'Medium';
export const srcBadge=(s:string)=>s==='gmail'?'<span class="task-badge badge-gmail">✉ Gmail</span>':s==='email_in'?'<span class="task-badge badge-email">📱 Email-in</span>':s==='text_in'?'<span class="task-badge badge-email">💬 Text-in</span>':s==='sms_in'?'<span class="task-badge badge-email">📲 SMS-in</span>':s==='messages'?'<span class="task-badge badge-email">💬 Messages</span>':s==='sms'?'<span class="task-badge badge-email">📲 SMS</span>':s==='recurring'?'<span class="task-badge badge-manual">↻ Recurring</span>':'<span class="task-badge badge-manual">Manual</span>';
export function emailStamp(t:Task){ const d=parseJson(t.source_details).email_date||t.created_at; if(!d||t.source!=='gmail') return ''; return new Date(d).toLocaleDateString('en',{month:'short',day:'numeric'}); }
export function tagLabel(t:Task){ const m=(t.tags||'').match(/project:([^,]+)/); return m?m[1]:isSomeday(t)?'Someday / Maybe':''; }
export async function dbQuery(sql:string){ const r=await fetch('/api/db/query',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({appId:APP_ID,sql})}); const d=await r.json(); return d.rows||[]; }
export async function dbWrite(sql:string,params:any[]=[]){ const r=await fetch('/api/db/write',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({appId:APP_ID,sql,params})}), d=await r.json(); if(!r.ok) throw new Error(d.error||'Write failed'); return d; }
export async function triggerJob(jobId:string){ await fetch('/api/jobs/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jobId})}); }
export function activeTasks(tasks:Task[]){ return tasks.filter(t=>!isSomeday(t)); }
export const sortTasks=(rows:Task[])=>[...rows].sort((a,b)=>a.priority-b.priority||((a.due_date?0:1)-(b.due_date?0:1))||(a.due_date||'').localeCompare(b.due_date||'')||(b.created_at||'').localeCompare(a.created_at||''));
export function getFocusTasks(tasks:Task[]){ const {end}=weekBounds(); return sortTasks(activeTasks(tasks).filter(x=>{ if(x.status!=='open'||!x.due_date) return false; const due=new Date(x.due_date+'T12:00:00'); return due<=end; })); }
export function weekBounds(){ const d=new Date(),day=(d.getDay()+6)%7,start=new Date(d),end=new Date(d); start.setDate(d.getDate()-day); end.setDate(start.getDate()+6); start.setHours(0,0,0,0); end.setHours(23,59,59,999); return {start,end}; }
export function weekItems(items:CalendarItem[]){ const {start,end}=weekBounds(); return items.filter(i=>{ if(!i.event_date) return false; const x=new Date(i.event_date+'T12:00:00'); return x>=start&&x<=end; }); }
export function weekDays(){ const {start}=weekBounds(); return Array.from({length:7},(_,i)=>{ const d=new Date(start); d.setDate(start.getDate()+i); return {key:d.toISOString().slice(0,10),label:d.toLocaleDateString('en',{weekday:'short'}),day:d.toLocaleDateString('en',{month:'short',day:'numeric'})}; }); }
export function fmtEvent(i:CalendarItem){ const day=i.event_date?new Date(i.event_date+'T00:00:00').toLocaleDateString('en',{weekday:'short',month:'short',day:'numeric'}):'No date'; return i.starts_at?`${day} · ${i.starts_at}`:`${day} · All day`; }
const clean=(s='')=>s.replace(/<[^>]+>/g,' ').replace(/["<>]/g,'').replace(/\s+/g,' ').trim();
const entity=(t:Task)=>{ const m=parseJson(t.source_details), body=clean(sourceBody(t)), from=clean((m.provider||m.from||m.contact||'').replace(/.*</,'').replace(/>.*/,'').replace(/^\+?1?\d+$/,'')), hit=body.match(/(?:from|with|at) ([A-Z][A-Za-z&'\-.]+(?: [A-Z][A-Za-z&'\-.]+){0,4})/), store=body.match(/[:\-]\s*([A-Z][A-Z&\-.]{1,20})\b/); return clean(hit?.[1]||store?.[1]||from).replace(/^(Hello|Hi)\s+\w+,?\s*/i,'').replace(/\b(via .*|message|statement|appointment)\b.*$/i,'').trim(); };
const imperative=(s='')=>/^(pay|review|respond|reply|confirm|schedule|file|send|call|email|pick up|make|talk|follow up|submit|check|renew|go through)\b/i.test(s.trim());
export const sourceMeta=(t:Task)=>{ const m=parseJson(t.source_details); return [t.source==='gmail'||t.source==='email_in'?['From',m.from]:['Contact',m.contact],['Date',m.email_date||m.message_date||t.created_at],['Subject',m.subject],['Thread',m.chat_identifier||m.thread_id],['Source',t.source]].filter(([,v])=>v); };
export const sourceBody=(t:Task)=>parseJson(t.source_details).body_preview||parseJson(t.source_details).notes||t.description||t.title;
export const waitingState=(t:Task)=>{ const m=parseJson(t.source_details),s=`${smartTaskTitle(t)}
${t.description||''}
${sourceBody(t)||''}`.toLowerCase().replace(/[^a-z0-9\s]/g,' '),has=(r:RegExp)=>r.test(s); if(m.reason==='reply'||has(/(reply|respond|response|hear back|follow up|circle back|let me know|get back to|reach out|call|email|text|talk to|check with)/)) return {kind:'reply',label:'Waiting for reply'}; if(has(/(approve|approval|sign off|authorized?|consent|review and approve|decision|decide|reconsideration)/)) return {kind:'approval',label:'Waiting for approval'}; if(has(/(confirm|confirmation|rsvp|availability|schedule|reschedule|book|check in|appointment|meeting time|pick a time)/)) return {kind:'scheduling',label:'Waiting for scheduling'}; if(has(/(waiting on|pending|after they|once they|needs .* to|when .* sends|waiting for|awaiting)/)) return {kind:'external',label:'Waiting for someone else'}; return null; };
export const waitingBadge=(t:Task)=>waitingState(t)?.label||'';
export function smartTaskTitle(t:Task){ const raw=clean(t.title||''), body=clean(sourceBody(t)||raw), lower=body.toLowerCase(), who=entity(t); if(!raw) return 'Task'; if(t.source==='manual'||t.source==='recurring'||imperative(raw)) return raw; if(/ready for pick\s*up|ready for pickup/.test(lower)&&/(rx|prescription|pharmacy|refill)/.test(lower)) return `Errand: Pick up prescription${who?` from ${who}`:''}`; if(/statement .*available|available to pay|pay online|balance due|invoice/.test(lower)) return `Make a payment${who?`: ${who}`:''}`; if(/past due|overdue|bill is due/.test(lower)) return `Pay bill${who?`: ${who}`:''}`; if(/tax|efile|extension filed|documents?/.test(lower)&&/(file|submit|send|available)/.test(lower)) return `File paperwork${who?`: ${who}`:''}`; if(/claim|claim form|reimbursement/.test(lower)) return `Submit claim${who?`: ${who}`:''}`; if(/confirm|let me know|can you|could you|please respond|reply/.test(lower)) return `Reply${who?`: ${who}`:''}`; if(/schedule|book|reschedule/.test(lower)) return `Schedule${who?`: ${who}`:''}`; return raw.replace(/^(hello|hi)\s+\w+,?\s*/i,'').replace(/^this is\s+/i,'').replace(/^calendar event:\s*/i,'').slice(0,120); }
